name: K6 Performance Testing

on: [push]

jobs:
  k6_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Local Server
        # Запускаємо сервер у фоні, щоб він не блокував наступні кроки
        run: python3 -m http.server 8080 & 

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: performance-tests/load-test.js

      - name: Run k6 Smoke Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: performance-tests/smoke-test.js

      - name: Run k6 Stress Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: performance-tests/stress-test.js
